=Handling Transactions in JMS
:keywords: jms, connector, transactions, transactional
:toc:
:toc-title:

The JMS Connector provides support for executing its operations in a transactional way OOTB using Mule's 'transactionalAction' configuration.

In order to execute an operation as part of the transaction, we have the following two options.

== Processing New Messages With Transactional Session

If you want a JMS Listener to use a transactional session when dispatching the messages, you should set the 'transactionalAction' to 'ALWAYS_BEGIN':

[source, xml, linenums]
----
<jms:listener config-ref="JMS_Config" destination="${originQueue}" transactionalAction="ALWAYS_BEGIN"/>
----

With this configuration, each new message will be processed in a transaction that is propagate to all the flow's components and is commited once the flow execution is completed successfully. The transaction will be rolledback if the flow execution is completed with an error.

By default, *other components* in the flow *will not join the transaction* created by the listener. In order to execute other operations using the listener’s transaction, you must declare them either with 'ALWAYS_JOIN', or 'JOIN_IF_POSSIBLE'.

== Execute Operations As Part Of A Transaction

To execute an operation like 'publish' or 'consume' as part of a transaction, we have to set the 'transactionalAction' to 'ALWAYS_JOIN', or 'JOIN_IF_POSSIBLE':

This operations can join a transaction initiated by the listener:
[source, xml, linenums]
----

<flow name="joiningToListenerTransaction">
    <jms:listener config-ref="JMS_Config" destination="${originQueue}" transactionalAction="ALWAYS_BEGIN"/>
    <jms:publish config-ref="JMS_Config" destination="#[attributes.properties.userProperties.redirectDestination]" transactionalAction="JOIN_IF_POSSIBLE"/>
    <jms:consume config-ref="JMS_Config" destination="#[attributes.properties.userProperties.callbackDestination]" transactionalAction="JOIN_IF_POSSIBLE"/>
</flow>
----

Or they can join an scoped transaction:
[source, xml, linenums]
----
<flow name="nonTxPublishMustNotJoinCurrentTx">
    <http:listener config-ref="HTTP_Config" path="/orders"/>
    <try transactionalAction="ALWAYS_BEGIN">
        <jms:publish config-ref="config" destination="${billingService}" transactionalAction="ALWAYS_JOIN"/>
        <jms:publish config-ref="config" destination="${shipmentService}" transactionalAction="ALWAYS_JOIN"/>
        <jms:publish-consume config-ref="JMS_Config" destination="${invoicesVerificationService}" transactionalAction="ALWAYS_JOIN"/>
        <validation:is-true expression="#[payload]"/>
    </try>
</flow>
----



