= About the JMS Connector
:keywords: jms, connector, jms_1.0.2b, jms_1.1, jms_2.0
:toc:
:toc-title:

Release Notes: link:/release-notes/connector-jms-1.1.0[Mule Runtime JMS 1.1.0 Release Notes]

The JMS connector enables your application to do messaging using the JMS implementation of your choice. Its main features include:

* Pub/Sub pattern support on any given destination.
* Listen/Reply pattern support on any given destination.
* Publish-Consume pattern support on any given destination, with fixed or temporary reply Queue.
* Fully compliant with JMS 2.0, 1.1 and 1.0.2 specifications.

[[configuration_settings]]
== Configuring the connector

Out of the box, the JMS connector comes with a fine tunned set of default values, both for publishing and consuming messages. This means that the only requirement is for you to configure which connection should be used.

This example sets a minimal connection to an in-memory ActiveMQ broker the JMS connector:

[source, xml, linenums]
----
<jms:config name="JMS_Config">
  <jms:active-mq-connection/>
</jms:config>
----

=== Defining Global Defaults

The JMS 'config' allows you to define multiple parameters that will be used as a default while consuming or publishing messages. This way, you can define a global default behaviour for all the operations associated the config and then override each parameter only in the operations that require a custom behaviour.

For example, we can define a default 'selector' behaviour when consuming a Message in any of the operations that are associated to this config, and also a default

[source, xml, linenums]
----
<jms:config name="JMS_Config">
  <jms:active-mq-connection/>
  <jms:consumer-config selector="JMSType = 'INVOICE'"/>
  <jms:producer-config timeToLive="60000"/>
</jms:config>
----

In this case, every operation 'consume' or 'listener' associated to this config will use this 'selector' by default, while every time we do a 'publish' or 'publish-consume', the outgoing Message will have a TTL of 60 seconds.

All of this properties can be overriden at operation level when required. Let's say we need to 'publish' a Message with a shorter TTL, we can do so using this config and overriding the parameter:

[source, xml, linenums]
----
<jms:publish config-ref="JMS_Config" timeToLive="10000"/>
----


[[connection_settings]]
== Connecting to a Broker

A JMS connection is defined by a set of general parameters that apply for any connection, as well as particular configurations related to the actual broker implementation that's going to be used.

=== Selecting the JMS Spec

The main common parameter is the JMS 'specification', used to select between all the supported specs, which are '2.0', '1.1' and '1.0.2b'. This 'specification' must be supported by the broker implementation associated to this connection, otherwise the connection will fail.
Features available only in JMS '2.0' won't work with any other 'specification'.

=== Providing Credentials For Authentication

In order to do stablish an authenticated connection, you need to configure the 'username' and 'password' in the 'connection' element:

[source, xml, linenums]
----
<jms:config name="JMS_Config">
  <jms:active-mq-connection username="${env.user}" password="${env.pass}"/>
</jms:config>
----


=== Configuring Connections Caching

The JMS Connector allows you to configure which 'caching-strategy' to use when creating new Connections. By default, the connections caching is enabled both for Message consumers and producers and will preserve as many connections as possible.

Customizing the cache configuration can be done directly in the connection declaration:

[source, xml, linenums]
----
<jms:config name="JMS_Config">
  <jms:active-mq-connection>
    <jms:caching-strategy>
      <jms:default-caching cacheConsumers="false"/>
    </jms:caching-strategy>
  </jms:active-mq-connection>
</jms:config>
----

In the same way, you can completely disable the caching of Connections using the 'no-caching' option:

[source, xml, linenums]
----
<jms:config name="JMS_Config">
  <jms:generic-connection connectionFactory="customConnectionFactory">
    <jms:caching-strategy>
        <jms:no-caching/>
    </jms:caching-strategy>
  </jms:generic-connection>
</jms:config>
----

=== Identifing The Connection Client

The purpose of client identifier is to associate a connection and its objects with a state maintained on behalf of the client by a provider, and it is *mandatory* for identifying an unshared durable subscription.

[source, xml, linenums]
----
<jms:config name="JMS_Config">
  <jms:active-mq-connection clientId="${env.clientId}"/>
</jms:config>
----

By definition, the client state identified by a 'clientId' can be "in use" by only one Connection at a time.


== Connecting To ActiveMQ

Support for ActiveMQ 5 is provided out of the box by the connector using the 'active-mq-connection'. With this connection, you can use both JMS 1.1 (the default) or JMS 1.0.2b specs, and configure all the general connection parameters for JMS, as well as the custom parameters only present in ActiveMQ.

Once we declare the 'active-mq-connection', all that's left to do is set up the connection factory with our custom configuration. Every parameter in the connection comes with a default value, meaning that you are required to configure only the parameters relevant for your use case. Also, the ActiveMQ connection exposes parameters that are exclusive of ActiveMQ implementation, like 'initialRedeliveryDelay'.

An example of a simple configuration of an ActiveMQ connection would be:

[source, xml, linenums]
----
<jms:config name="JMS_Config">
  <jms:active-mq-connection initialRedeliveryDelay="2000" brokerUrl="tcp://localhost:61616"/>
</jms:config>
----

== Using Different Brokers

In cases where ActiveMQ 5 is not the chosen broker, we can use the 'generic-connection' to declare a connection to any broker implementation. Out of the box, the connector provides a JNDI based connection factory builder that allows to configure the connection using JNDI in the context of the application.

For example, if we want to connect with Artemis to use the JMS 2.0 spec, we could define our connection factory in this way:

[source, xml, linenums]
----
<jms:config name="JMS_Config">
    <jms:generic-connection specification="JMS_2_0">
        <jms:connection-factory>
            <jms:jndi-connection-factory connectionFactoryJndiName="ConnectionFactory" lookupDestination="ALWAYS">
                <jms:name-resolver-builder
                        jndiInitialContextFactory="org.apache.activemq.artemis.ActiveMQInitialContextFactory"
                        jndiProviderUrl="tcp://localhost:61616?broker.persistent=false&amp;broker.useJmx=false">
                    <jms:provider-properties>
                        <jms:provider-property key="queue.jndi-queue-in" value="in.queue"/>
                        <jms:provider-property key="topic.jndi-topic-in" value="in.topic"/>
                    </jms:provider-properties>
                </jms:name-resolver-builder>
            </jms:jndi-connection-factory>
        </jms:connection-factory>
    </jms:generic-connection>
</jms:config>
----

If you have configured a JNDI context on the connector, you can also look up destinations via JNDI using the 'lookupDestination' attribute, which provides three different configurations:

* NEVER: No lookup is done and the destinations are created using the existing JMS session.
* TRY_ALWAYS: First try to find the destination using JNDI, and in case it doesn't exist, create it using the current JMS Session.
* ALWAYS: If a queue/topic cannot be found via JNDI, fail with a 'JMS:DESTINATION_NOT_FOUND' error

For more information regarding the 'generic-connection' or 'jndi-connection-factory', please see link:jms-documentation[the connector reference docs].


== See Also
* link:jms-consume[How To Consume Messages]
* link:jms-publish[How To Publish Messages]
* link:jms-listener[How To Listen For New Messages]
* link:jms-publish-consume[How To Listen For A Reply]
* link:jms-ack[Handling Message Acknowledgement]
* link:jms-transactions[Handling Transactions in JMS]
* link:jms-documentation[JMS Connector Technical Reference]
